### ISSUE TITLE
Feat - Puesta en marcha del Servidor de Integración Continua con el repositorio de código.

### ISSUE THREAD

**Issue by Samalbalat** [juanlo017/decide-single-tragabuche-I#13]
La tarea es autodescriptiva

**Comment by juanlo017** [comment]
Explicación de la issue: Se debe crear un workflow de integracion continua que se ejecute en el repositorio de codigo

Responsable de la Resolución: juanlo017

Responsable de la Revisión: pabcueper

Fecha de Reporte: 08/11/2023

Fecha Estimada de Resolución: 15/11/2023
