### ISSUE TITLE
Issue - Error en Votación Si/No

### ISSUE THREAD

**Issue by javgrogom** [juanlo017/decide-single-tragabuche-I#29]
Explicación de la issue: Implementación de la votación Si/No a la hora de crearla desde la interfaz de administrador

Responsable de la Resolución: alisanhos

Responsable de la Revisión: javgrogom

Fecha de Reporte: 28/11/2023

Fecha Estimada de Resolución: 08/12/2023

Cómo se Reproduce el Fallo (si procede):

1. Crear una 'question' nueva, eligiendo el 'type' : 'Yes or No Question'.
2. Escribir cualquier cosa en las opciones y darle al boton 'SAVE'
3. Salta una pantalla amarilla con un error
![image](https://github.com/juanlo017/decide-single-tragabuche-I/assets/72520174/4c28f762-e46b-494c-a66a-40fce2398005)

Prioridad del Fallo (si procede): Media

Estado del Fallo (si procede): To Do

Tipo de Fallo (si procede): Funcionamiento indebido.

Notas Adicionales (si procede): preferible sería que saliera un aviso debajo de las casillas en blanco con un mensaje del corte "this must be blank", en lugar de salir la pantalla amarilla de error

**Comment by alisanhos** [comment]
Error corregido, siguiendo el consejo comentado por el compañero.
![imagen](https://github.com/juanlo017/decide-single-tragabuche-I/assets/59439742/6aaee102-ca0e-4313-a726-bf4cf70ca404)
