### ISSUE TITLE
Feat - Definición/Administración Votación Sí/No

### ISSUE THREAD

**Issue by Samalbalat** [juanlo017/decide-single-tragabuche-I#3]
Crear una funcionalidad que permita las votaciones del tipo Sí/No junto con las funcionalidades subyacentes para que sean manejadas por sistema

**Comment by alisanhos** [comment]
Explicación de la issue: Implementacion de Preguntas tipo Yes or No. 

    Responsable de la Resolución: alisanhos

    Responsable de la Revisión: javgrogom

    Fecha de Reporte: 14/11/2023

    Fecha Estimada de Resolución: 25/11/2023

    Cómo se Reproduce el Fallo (si procede): No procede

    Prioridad del Fallo (si procede): No procede

    Estado del Fallo (si procede): No procede

    Tipo de Fallo (si procede): No procede

    Notas Adicionales (si procede): No procede

**Comment by alisanhos** [comment]
Commited in 605e365
