### ISSUE TITLE
Issue - Error en interfaz de votación si/no: Duplicados

### ISSUE THREAD

**Issue by javgrogom** [juanlo017/decide-single-tragabuche-I#30]
Explicación de la issue: Interfaz de usuario a la hora de realizar una votación si/no, salen Yes o No de forma duplicada.

Responsable de la Resolución: alisanhos

Responsable de la Revisión: javgrogom

Fecha de Reporte: 28/11/2023

Fecha Estimada de Resolución: 08/12/2023

Cómo se Reproduce el Fallo (si procede):

1. Crear una 'question' nueva, eligiendo el 'type' : 'Yes or No Question'.
2. Escribir varias veces Yes o No en las opciones y darle al boton 'SAVE'
![Imagen de WhatsApp 2023-11-28 a las 21 36 33_4335a8a9](https://github.com/juanlo017/decide-single-tragabuche-I/assets/72520174/fb80c8bf-0468-4233-b3c8-1dba70ea337b)
3. Se crea la Question
4. Creamos la votación
5. Ingresamos a la votación por medio de la interfaz de usuario, y veremos que sale Yes o No duplicado tantas veces como los metamos en la Question
![Imagen de WhatsApp 2023-11-28 a las 21 34 13_debed511](https://github.com/juanlo017/decide-single-tragabuche-I/assets/72520174/9c175827-f9ab-4b35-86b4-dda7151f973d)
6. Votamos y se almacena correctamente, solo con 1 yes y 1 no
![Imagen de WhatsApp 2023-11-28 a las 21 38 47_399c6778](https://github.com/juanlo017/decide-single-tragabuche-I/assets/72520174/c0fddd3c-970c-48ee-acee-9e9a7be45db7)
7. Al ingresar al recuento de la votación, el Yes No sale duplicado tantas veces como lo metamos en los parámetros de Question
![Imagen de WhatsApp 2023-11-28 a las 21 45 32_f59fd101](https://github.com/juanlo017/decide-single-tragabuche-I/assets/72520174/fd13f6e2-3af3-41ba-9097-c174e63076f7)

Prioridad del Fallo (si procede): Baja

Estado del Fallo (si procede): To Do

Tipo de Fallo (si procede): Funcionamiento indebido.

Notas Adicionales (si procede): No procede

**Comment by alisanhos** [comment]
Como se tenia previsto, al crear una votación de tipo Yes or No, no se debía escribir en las opciones abajo ya que las respuestas se generan automáticamente al marcar la casilla de 'Yes or No Question'. Para solucionar el error de duplicado, hemos puesto que no te permita escribir en las opciones:
![imagen](https://github.com/juanlo017/decide-single-tragabuche-I/assets/59439742/5c825a2c-4d3e-40eb-b24b-c0132c8752d9)
