### ISSUE TITLE
Feat - Registro de Usuarios

### ISSUE THREAD

**Issue by Samalbalat** [juanlo017/decide-single-tragabuche-I#4]
Crear un sistema de registro de usuarios para la aplicación

**Comment by juanlo017** [comment]
- Explicación del Fallo:

- Cómo se Reproduce el Fallo:

- Prioridad del Fallo: 

- Estado del Fallo: 

- Tipo de Fallo: 

- Notas Adicionales: 

- Responsable(s) de la Resolución:

- Responsable de la Revisión:

- Fecha de Reporte: 

- Fecha Estimada de Resolución:
