### ISSUE TITLE
Feat - Post procesado

### ISSUE THREAD

**Issue by Samalbalat** [juanlo017/decide-single-tragabuche-I#5]
Crear una funcionalidad de postprocesado para incluir el algoritmo de paridad y cuenta de borda

**Comment by pabcueper** [comment]
Explicación de la issue: Implementación de la funcionalidad de registros de nuevos usuarios

Responsable de la Resolución: juanlo017, pabcueper

Responsable de la Revisión: samalbalat

Fecha de Reporte: 14/11/2023

Fecha Estimada de Resolución: 27/11/2023

Cómo se Reproduce el Fallo (si procede): No procede

Prioridad del Fallo (si procede): No procede

Estado del Fallo (si procede): No procede

Tipo de Fallo (si procede): No procede

Notas Adicionales (si procede): No procede
