### ISSUE TITLE
Feat - Hacer la Interfaz traducible / Traducir al español y otros idiomas (en, ca, de, eo, fr, it, pt, ga, gd, tr, gl)

### ISSUE THREAD

**Issue by Samalbalat** [juanlo017/decide-single-tragabuche-I#6]
Hacer que la aplicación disponga de varios lenguajes de traducción entre ellos el español

**Comment by javgrogom** [comment]
Explicación de la issue: Implementación de la funcionalidad de traducción de la aplicación en la interfaz de los usuarios y la posibilidad de alternar entre diferentes idiomas. Traducción a los siguientes idiomas: español, ingles, catalan, aleman, esperanto, frances, italiano, portugues, irlandes, escoces, turco, gallego


Responsable de la Resolución: javgrogom

Responsable de la Revisión: javgrogom, alisanhos

Fecha de Reporte: 11/11/2023

Fecha Estimada de Resolución: 25/11/2023

Cómo se Reproduce el Fallo (si procede): No procede

Prioridad del Fallo (si procede): No procede

Estado del Fallo (si procede): No procede

Tipo de Fallo (si procede): No procede

Notas Adicionales (si procede): Esta issue solo abarca las traducciones a los idiomas especificados en las interfaces existentes en el momento de su creación, para futuras interfaces y traducciones, junto a errores que surjan se abrirán nuevas issues que las especifiquen
